# Full path to the nft binary.
# Optional. Default is /usr/sbin/nft
nft_binary:
  - /path/to/nft
# List of additional nameservers that the resolver will use.
# Optional, the resolver will always use the nameservers listed
# in /etc/resolv.conf, and these addtional ones if provided.
dns_nameservers:
  - 1.1.1.1
  - 8.8.8.8
  - 9.9.9.9
sets:
  # The name of the set as it appears in nftables.
  dns_ip:
    # The table family.
    family: inet
    # The table name.
    table: input
    # The plugin used to generate the updated list of elements for the set.
    # Must be the filename of the plugin in the plugin directory, without
    # the extension.
    plugin: resolv
    # The strategy for the update, one of:
    #   add: Only add new elements
    #   update: Update the elements in place, first adding new elements,
    #           then removing existing elements that don't match the new
    #           set.
    #   replace: Replace the old elements with the new
    strategy: replace
    # Metadata is data that gets passed directly to the instance of the plugin
    # that will generate the new elements.
    netadata:
      foo: bar
