# Required, class name must be 'GetElements'.
class GetElements(object):

    def __init__(self, logger, metadata):
        # The logger instantiated for this plugin.
        self.logger = logger
        # Any metadata from the configuration for the set.
        self.metadata = metadata

    # The one required method, must return the list of elements generated by
    # the call to the plugin.
    def get_elements(self):
        return [
            '1.1.1.1',
        ]
