import sys
sys.path.append('..')
from plugins import Plugin
from file_retriever import FileRetriever

DEFAULT_JSON_URL = "https://www.example.com/ip_ranges_file"

# Required, class name must be 'GetElements', and must extend the 'Plugin'
# class.
class GetElements(Plugin):

    def __init__(self, metadata, resolver, logger, config, args):
        super().__init__(metadata, resolver, logger, config, args)
        # self.metadata: Any metadata from the configuration for the set.
        # self.resolver: Configured instance of berserker_resolver.
        #                If args.berserk is set, then berserker_ips will
        #                be used as well to resolve hostnames.
        # self.logger: The logger instantiated for this plugin.
        # self.config: Loaded configuration file.
        # self.args: Any parsed command line args.

        # An example of how to instantiate FileRetriever class.
        self.url = 'url' in metadata and metadata['url'] or DEFAULT_JSON_URL
        self.cache_file = 'cache_file' in metadata and metadata['cache_file'] or None
        self.file_retriever = FileRetriever(self.logger, self.url, self.cache_file)

    # The one required method, must return the list of elements generated by
    # the call to the plugin.
    def get_elements(self):
        # Also has a 'get_json()' method.
        data = self.file_retriever.get()
        if data:
            elements = data.split()
            return elements
        return False
